### ISSUE TITLE
Does rtorrent seed if openvpn is not connected?

### ISSUE THREAD

**Issue by calgara12** [h1f0x/rtorrent-flood-openvpn#10]
Hey, I just got my docker container up and running. 
Now i'm wondering if there is kind of a security measure if for whatever reason openvpn fails to connect, or will rtorrent start seeding without the vpn?

Thanks.

**Comment by h1f0x** [comment]
as far as I remember the container will not be able to connect to the internet at all if the vpn stops working, but this should be verified. :)
