### ISSUE TITLE
systemd couldn't start rtorrent - did a bunch of stuff - still not working

### ISSUE THREAD

**Issue by averyfreeman** [h1f0x/rtorrent-flood-openvpn#6]
Hi

After failing to compile librtorrent with xmlrpc-c (can't find boost even though installed, flags do nothing) I get frustrated and decide to take a shot at deploying my first container.  I'm using podman on Fedora 30 server VM in esxi 6.7U2.

Here's what happened:

1. Started container.  Appears to work fine with podman (should, right?) and flood connects at VM's IP:8000, but no rtorrent to connect to. Supplied credentials tried several times to no avail, so logged into container w/ bash. 

2. A-hah.  Can't get systemd to start rtorrent inside the container.  Doesn't give very good feedback as to what's wrong, so I start googling.

3. Arch forum has a hint: Systemctl doesn't support %h for home so changed %h to /home/rtorrent

4. Still can't get rtorrent service started.  Then I realize config file wasn't in /home/rtorrent/config so copied generic from defaults.

5. Then I got systemctl to start rtorrent with the generic config, but I don't know anything about rtorrent, so guessing I try to uncomment stuff related to xmlrpc because I still can't connect from flood.

6. Now I can't copy config back because container RO.  Could probably copy if I stopped the container, but at this point I decide to give up.  This is enough stuff I think it's probably worth it to file a bug report.

You know what would be really helpful?  Can you post a copy of your rtorrent.rc file so if there's an issue with the container's copy they'll have one to put in their /path/to/config ?  Maybe tell people to put it there?

(I know it should be intuitive but for people like me without any rtorrent experience I didn't really know...)

Thanks!

**Comment by h1f0x** [comment]
Hi there,

Thank you for your feedback and sorry you had such trouble to deploy it! I will see if i can make it simpler!

The example config file you can find at: https://github.com/h1f0x/rtorrent-flood-openvpn/tree/master/rootfs/defaults/config/rtorrent

Cheers!

**Comment by averyfreeman** [comment]
Perfect! thank you, I appreciate it :)
