### ISSUE TITLE
Not convinced rtorrent is using VPN tunnel

### ISSUE THREAD

**Issue by Altycoder** [h1f0x/rtorrent-flood-openvpn#9]
If I provide a ovpn file and credentials I can download using rtorrent but if I remove these from the vpn folder and recreate the container, rtorrent still downloads successfully - does this mean that rtorrent is incorrectly configured? Shouldn't the downloads cease if there is no VPN tunnel?

There is no openvpn log created in the VPN folder so perhaps the VPN isn't even connecting in the first place?

**Comment by Altycoder** [comment]
In addition I've just noticed that the IP address in "my-external-ip.txt" is the same as my ISP provided external IP address so this container is not functioning correctly so I'm shutting it down.

**Comment by h1f0x** [comment]
this container does what it says, there is not mentioned it will not connect to the internet, if the vpn is not up and I am not planing in changing this currently.
